on:
  push:
    tags:
      - 'v*' # trigger this when a tag starting with v is pushed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
name: Create Image from v-Tag
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: De-v the release tag
        id: de_v_tag
        run: |
          # Use the 'replace' function to remove the "v" from the tag
          TAG="${{ github.ref }}"
          TAG_WITHOUT_V="${TAG#refs/tags/v}"
          echo "Extracted tag: $TAG_WITHOUT_V"
          echo "tag_without_v=$TAG_WITHOUT_V" >> "$GITHUB_OUTPUT"
      - name: Show the modified tag
        run: |
          echo "Modified tag: Release ${{ steps.de_v_tag.outputs.tag_without_v }}"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

